### ISSUE TITLE
"Unable to get root" - "Today" shortcut unresponsive

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#101]
Click on "Today" in the top bar - nothing happens. Console shows "unable to get root"

<img width="378" alt="image" src="https://user-images.githubusercontent.com/1813419/234412799-983b2c11-ba90-44ba-af05-ac8ac92b6aee.png">

**Comment by progrium** [comment]
This looks like a problem with make. Normally make takes a name and it creates a node with no parent. However you can give it a path and it should try to use this as the parent for the new node. If part of the path doesn't exist, it should create it. This is a kind of complicated function, but it seems that path used for the todayNode (something like "@workspace/Calendar/blah/blah") makes it fail with unable to get root. In theory this is because `@workspace` is not a root node and is not a name but an ID, however because it is a system ID, it should be able to find it regardless and make this work. So it could be related to the `find` method, but it should be able to find `@workspace` and go from there as usual (finding or making the rest of the path).
