### ISSUE TITLE
app: add restrictions to search node

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#105]
**prevent adding children**
if you have a regular node below a search node and use the keyboard shortcut to move the node up into a search node's results, the regular node is added to the search node, but it isn't visible. we should prevent users from adding any kind of children nodes to a search node.

**prevent deleting search node children**
users should be able to rearrange search node results, but they shouldn't be able to delete the results (children).

**Comment by progrium** [comment]
We might want to have a way to flag nodes as "read-only" but for now we can probably assume if they implement the `objectChildren` hook the children are "managed" so we would:

* Not allow children to be deleted at the command level (or since they are references, ask if they want to delete the referenced node)
* Make sure move commands skip these nodes
* Prevent newline inserts (return key at end of node text)
* Prevent/skip node when indenting
* Prevent inserts relative to any of the children
* No create references (since effectively performs an insert)

Moving children "out" seems like it could be useful in some cases, but not really with search. However, it doesn't seem like its necessary to prevent it yet. 

Allowing user to re-arrange result nodes means persisting them. Right now they are created as temporary orphan nodes. If we instead create them as actual children to the search node (and perform a merge on subsequent searches), move operations should work and be persisted.
