### ISSUE TITLE
Prevent indenting/outdenting a field node

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#116]
This irreversibly breaks your workspace.

**Comment by progrium** [comment]
Since this needs to be reproduced, to fix your workspace once you've done this, you have to get the field ID, search your workspace.json for the node with that ID and remove the ID from any nodes that reference it (there can be more than one). In short, use the ID to nuke it from your workspace doc.

To get the ID, you can perform a command (like Cmd+K for pick-commands, which does nothing but shows command palette) and the console will log the command and params, including the node it was done on.

**Comment by progrium** [comment]
This should be as simple as returning early in the command if the node is a field. Currently, easiest way to tell if a node is a field is `node.raw.Rel === "Fields"`
