### ISSUE TITLE
Can't change theme in Firefox

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#239]
in Firefox, try to change the theme. when you change the selection in the dropdown, the modal closes so you can't hit save.

https://share.getcloudapp.com/z8ubOB0Z

**Comment by ArcaTech** [comment]
This is really looking like a bug in Firefox. The form uses a standard HTML dialog and doesn't have any custom behavior for displaying or closing the modal. Considering it works as expected in Safari, it seems like an issue with Mozilla's implementation.

I tried changing the form by removing `method="dialog"` and adding `formmethod="dialog"` to the Cancel button, but it still doesn't work in Firefox (but is fine in Safari).

One fix might be to redo the way form/dialog handling works (with more custom behavior instead of using the `dialog` element). @progrium what do you think?
